### ISSUE TITLE
Design Sign-in Page

### ISSUE THREAD

**Issue by Link196** [mgamlem3/Energy-Dashboard#105]
**Details**
Design sign-in page to allow authentication of users when accessing the management page.

**Pre-Requisites**
None

**Estimated Time**
2 hrs

**Difficulty**
- [ ] 3 
- [x] 5
- [ ] 8
- [ ] 13
- [ ] 20
- [ ] 40

**Comment by Link196** [comment]
The page itself is designed and requires the user to enter a username and password, but authentication is not yet set up, so it accepts anything as long as something is entered in each box.

**Comment by mgamlem3** [comment]
Whenever you feel as though it is ready for me to begin putting in auth will you please close the issue so I know I can start?

**Comment by Link196** [comment]
Will do. I'm working on getting the "remember me" check box working.

**Comment by Link196** [comment]
The functionality of the "remember me" check box might need to be handled by the authentication, but I'm not sure.

**Comment by Link196** [comment]
We can also just remove it, since Whitworth SSO doesn't have that option. I'm going to go ahead and close this issue and merge into testing, and we can decide the fate of the check box later.

**Comment by Link196** [comment]
Completed in #133
