### ISSUE TITLE
Make function/API Route to get/post current power cost

### ISSUE THREAD

**Issue by mgamlem3** [mgamlem3/Energy-Dashboard#111]
**Details**
Should just be one value that can be changed when desired by page managers

**Pre-Requisites**
none

**Estimated Time**
.5 hr

**Difficulty**
- [x] 3 
- [ ] 5
- [ ] 8
- [ ] 13
- [ ] 20
- [ ] 40

**Comment by Link196** [comment]
I would say that this is probably done as of #169

**Comment by mgamlem3** [comment]
Merged into Andrew's branch with fix
