### ISSUE TITLE
Search Names for Buildings do not return data

### ISSUE THREAD

**Issue by mgamlem3** [mgamlem3/Energy-Dashboard#138]
**Describe the bug**
Search names are not the same ones being used by the Alerton reporting software. This causes our database to fail when searching for buildings.

**Comment by mgamlem3** [comment]
New fix works for me. @thildahl20 do you still have problems?

**Comment by thildahl20** [comment]
I'm not at my computer right now, but I'll be sure to check later!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
