### ISSUE TITLE
Unable to deselect buildings on building sidebar

### ISSUE THREAD

**Issue by mgamlem3** [mgamlem3/Energy-Dashboard#50]
**Describe the bug**
Once buildings are selected on the sidebar and highlight blue, they are unable to be un-selected

**Expected behavior**
I should be able to un-select buildings as I choose.
This is also a problem when I am only trying to pick one building to view at a time.

**To Reproduce**
Navigate to any page with the building sidebar and click multiple buildings in the sidebar.

**Screenshots**
<img width="1667" alt="Screen Shot 2019-03-12 at 2 17 02 PM" src="https://user-images.githubusercontent.com/17277349/54236745-9038b580-44d1-11e9-8a81-84eda3cb0061.png">

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Comment by mgamlem3** [comment]
@thildahl20 I elevated the severity of this issue because it needs to be rectified before more work can be done on this graph.

**Comment by mgamlem3** [comment]
https://reactjs.org/docs/lists-and-keys.html#keys
This may be helpful in fixing this problem. It may also help solve an issue in #46 
You may just need to add a field like `key=1` and so on.

**Comment by Link196** [comment]
Fixed in #62
