### ISSUE TITLE
Fix interface scaling

### ISSUE THREAD

**Issue by Link196** [mgamlem3/Energy-Dashboard#56]
**Details**
Current design uses bootstrap rows, columns and containers to structure webpage. This helps when resizing, but the slider bar does not fit each user's individual screen. Need to remove hard coded pixel values for images and list items to make sure everything fits the screen perfectly. Should adjust dynamically. Possible solution is basing sizes on view window sizes (ex. 1vh)

**Pre-Requisites**

**Estimated Time**
1 hr

**Difficulty**
- [ ] 3 
- [ ] 5
- [X] 8
- [ ] 13
- [ ] 20
- [ ] 40

**Comment by Link196** [comment]
Fixed in pull request #59

**Comment by mgamlem3** [comment]
Discovered that #59 did not fix the issue completely.

**Comment by Link196** [comment]
Fixed in #65
