### ISSUE TITLE
Design Display Page

### ISSUE THREAD

**Issue by thildahl20** [mgamlem3/Energy-Dashboard#57]
**Details**
Must show meaningful graph data for long term display. This could be for dorm competitions on energy savings. It should show energy saved relative to building size for multiple buildings at once using graphs. May also contain other competition elements such as current leader

**Pre-Requisites**

**Estimated Time**
6 hrs

**Difficulty**
- [ ] 3 
- [ ] 5
- [ ] 8
- [X] 13
- [ ] 20
- [ ] 40

**Comment by mgamlem3** [comment]
This page should also be able to scroll/switch between data to get all comparisons/buildings on the screen at least one time per cycle.

**Comment by mgamlem3** [comment]
#67
