### ISSUE TITLE
Incorrect Spacing for Logo on Display Page

### ISSUE THREAD

**Issue by mgamlem3** [mgamlem3/Energy-Dashboard#78]
**Describe the bug**
The logo renders further to the right on the display page when compared to other pages. I wonder if this is because of the extra link that is rendered before the image.

**Expected behavior**
Logo should render along left border

**To Reproduce**
Build Andrew's branch

**Screenshots**
<img width="1680" alt="Screen Shot 2019-04-05 at 1 00 03 PM" src="https://user-images.githubusercontent.com/17277349/55653249-cb619800-57a2-11e9-8e63-ab1a447d8942.png">

**Comment by mgamlem3** [comment]
Additionally, I wonder if it would be good to add some left margin to the logo so that it renders a little from the left margin
<img width="587" alt="Screen Shot 2019-04-05 at 1 01 47 PM" src="https://user-images.githubusercontent.com/17277349/55653329-02d04480-57a3-11e9-9c8f-d61a9fb57532.png">
I'd check the style guide on this and see if there is a minimum spacing requirement.

**Comment by Link196** [comment]
I think the display page issue is due to the fact that it is part of the nav bar, and the nav bar has a bit of spacing to avoid having buttons right at the edge.

**Comment by mgamlem3** [comment]
Can we take it out of the nav bar component and just have it be the clickable logo with some new spacing on the left side?

**Comment by Link196** [comment]
Possibly, but I couldn't figure out how to make the logo clickable without putting it in the nav component. If someone else wants to try, that's fine, and/or I can take another look at it this weekend.

**Comment by mgamlem3** [comment]
https://www.w3schools.com/html/html_links.asp

**Comment by Link196** [comment]
Fixed in #83
