### ISSUE TITLE
Possibility of NoSQL Injection

### ISSUE THREAD

**Issue by Utsal20** [mgamlem3/Energy-Dashboard#94]
**Description**
With using unvalidated values received through the api call, there are possibilities of NoSQL injection. I know Pete escapes the strings; somewhere to start looking into fixes.
  
**Priority**
4/5 *aka just fix it, Michael*

**Comment by mgamlem3** [comment]
https://stackoverflow.com/questions/13436467/javascript-nosql-injection-prevention-in-mongodb

**Comment by mgamlem3** [comment]
#119 fixes this bug
